title: CNMAIN
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mananahmed.github.io" # update this to your GitHub Pages URL or custom domain
author:
  name:mananahmed
theme: minima
plugins: []