title: CM Naim
description: Archived Website of Prof CM Naim (3 June 1936 - 9 July 2025)
url: "https://cmnaim.com"
baseurl: ""
theme: minima
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
