title: "CM Naim"
email: "you@example.com"
description: "Personal site converted from WordPress to Jekyll"
baseurl: ""
url: "https://cmnaim.com"
github_repo: "https://github.com/mananahmed/cmnaim"
theme: "none"
plugins: []
paginate: 10
permalink: "/:categories/:year/:month/:day/:title/"